version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
      - ../data:/app/data
    environment:
      ALLOW_HOSTS: "127.0.0.1,localhost"
      ALLOW_ORIGINS: "http://127.0.0.1:8000,http://localhost:8000"
